name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: NPM Install
        run: npm install

      - name: Setup Vals
        run: |
          git config --global user.email "max@tjmc.ru"
          git config --global user.name "GitHub Actions"

      - name: Build Package
        run: npm run build
